language: bash
services: docker

env:
  - DOCKER_REPO=aws-cli-git

install:
  - ls
  # - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - TOKEN=$( curl -sSLd "username=${DOCKER_HUB_USERNAME}&password=${DOCKER_HUB_PASSWORD}" https://hub.docker.com/v2/users/login | jq -r '.token' )
  - NEW_TAG=$( curl -fsSL 'https://pypi.org/pypi/awscli/json' | jq -r '.info.version' )
  - "CURRENT_TAG=$( curl -sH \"Authorization: JWT ${TOKEN}\" \"https://hub.docker.com/v2/repositories/${DOCKER_HUB_USERNAME}/${DOCKER_REPO}/tags/${NEW_TAG}/\" | jq -r '.name' )"

script:
  - if [ $NEW_TAG = $CURRENT_TAG ]; then
      echo "Nothing new to build";
    else
      echo "Login to dockerhub";
      docker login -u ${DOCKER_HUB_USERNAME} -p ${DOCKER_HUB_PASSWORD};
      echo "Start building new image";
      travis_retry docker build --build-arg AWS_CLI_VERSION="${NEW_TAG}" -t "${DOCKER_REPO}" . ;
      echo "Push new image with tags";
      docker tag ${DOCKER_REPO} "${DOCKER_HUB_USERNAME}/${DOCKER_REPO}:latest";
      docker push "${DOCKER_HUB_USERNAME}/${DOCKER_REPO}:latest";
      docker tag "${DOCKER_HUB_USERNAME}/${DOCKER_REPO}:latest" "${DOCKER_HUB_USERNAME}/${DOCKER_REPO}:${NEW_TAG}";
      docker push "${DOCKER_HUB_USERNAME}/${DOCKER_REPO}:${NEW_TAG}";
    fi
  # - travis_retry docker build -t "$image" .

after_script:
  - docker images

# vim:set et ts=2 sw=2:
